### PR TITLE
fix lifetime validation failure for other node in welcomes

### LINKED ISSUE #2228: Error: Lifetime is not acceptable
Added my own local agent and its not streaming messages for this specific group as well :thinking_face:, these are the logs when i added it to the group

[Slack Message](https://xmtp-labs.slack.com/archives/C095DFN7YBG/p1752865875577019)

### PR DESCRIPTION
**Pull request by mchenani**
Context:
https://github.com/openmls/openmls/issues/1810

closes #2228

### CODE REVIEW

File: xmtp_mls/src/utils/test/mod.rs [hunk 1]
```diff
@@ -295,93 +293,3 @@ pub async fn wait_for_min_intents<C: ConnectionExt>(
     })
     .await
 }
-
```
Comment (mchenani) [inline xmtp_mls/src/utils/test/mod.rs:298]: moved this changes to make them easier to remove when mocking mechanism lands
